### ISSUE TITLE
Givtcp add-on does not restart when Home Assistant is restarted

### ISSUE THREAD

**Issue by kamenmackay** [britkat1980/giv_tcp#107]
I believe this only happens when Home Assistant is restarted via Developer Tools but I can test more if no-one else has encountered this issue.

**Comment by Tommo-101** [comment]
This is a non issue. Home assistant restart in developer tools doesn't restart addons. It only restarts home assistant core. Addons are running in their own kinda containers so have to be individually restarted or you have to restart the whole OS.

Not an issue with this addon, it's expected behaviour.
