### ISSUE TITLE
Upgrade path V2 to V3

### ISSUE THREAD

**Issue by Adrian57** [britkat1980/giv_tcp#297]
I can't find any info on upgrading V2to V3. Is there a way to do this automatically or is it an unistall of V2 and install of V3? Sorry to ask a question here but I can't find anything anywhere that answers this.

**Comment by gcoan** [comment]
When I upgraded from V2 to V3 I just stopped the V2 GivTCP add-on, unticked the 'start on boot', installed the V3 (they can sit alongside each other, no problem), and started the V3 add-on.

That's it.  Just make sure that you don't run V2 and V3 together at the same time.

Reverting back from V3 to V2 is as simple as stopping V3 and starting up V2.  I did that as well when I found issues with the early versions of V3

**Comment by Adrian57** [comment]
Things are so simple when explained simply! Thanks. Working perfectly in less than 10 minutes.

**Comment by SwiftRR** [comment]
I can add one more precaution for Predbat users.
If you are running Predbat and have an automatic restart set in your Predbat apps.yaml. For details, See 
https://springfall2008.github.io/batpred/apps-yaml/#automatic-restarts

If you upgrade from givTCP v2 to v3 and a communication error occurs, this auto restart may be initiated. If you don't change the addon id, you will find that v2 is restarted instead of your upgraded v3. You will then have both v2 and v3 running concurrently.
I learnt this from bitter experience.

Rob

**Comment by stevedundee2** [comment]
Thanks @gcoan . That simple approach seems to be working for me. There was a brief moment where it seemed broken, but I guess things just needed to get going properly and no obvious issues now. I'll keep v2 installed for a while, but I plan on uninstalling it in a day ot two.

**Comment by gcoan** [comment]
@stevedundee2 you can quite safely leave GivTCP v2 stopped in HA, it won't clash.

Do double check that your battery sensors are working OK with V3, when I originally upgraded I found that they weren't. @swiftrr has recently upgraded again to v3.0.4 and finds that they are still not working with his AC-coupled inverter

**Comment by gcoan** [comment]
> The SoC and the power flow for the battery match what the GivEnergy web dashboard is reporting, so I think all is well... Is there something else I should check for?

They're the main ones I would check, the battery power and the battery SoC (note battery SoC not inverter SoC)

**Comment by SwiftRR** [comment]
I have gone backwards and forwards between v2.4.9 and various v3 upgrades over last couple of months.
When I tried yesterday, v3.0.4 was looking good but the battery SOC and cell voltages were not changing.

I also have a chart for monitoring cell voltages over time and these stopped changing.
I am currently back in v2.4.9 which shows changing battery SOC and cell voltages.
I will try upgrading to v3.0.4 again this afternoon again and see if I can track down what is going wrong. 

The screenshots below shows what happened to me yesterday when I upgraded from v2.4.9 to v3.04.
<img width="750" alt="image" src="https://github.com/user-attachments/assets/8c68512e-2061-4127-ab22-af9619bbc593">

The top chart is the inverter SOC, which is fine.
The lower two charts are for my two batteries. You can see that the battery details did not change from about 13:30, when I upgraded to v3.0.4
I degraded back to v2.4.9 as about 20:30 pm and the battery details reappeared.

Rob

**Comment by stevedundee2** [comment]
Both those sensors are changing for me since I switched to V3.0.4. However they do not match each other (88% and 86%) - I don't know how normal that is, but both values are visible on the givenergy app. I think 88% might be the inverter and 86% the actual battery. So I am generally using the inverter value as it turns out, which is also what the givenergy app headlines with.

**Comment by sjs-1956** [comment]
Currently using v3.0.4. I have 1 Ac gen 1 inverter and two 8.4kWh batteries. At the moment my inverter reports 91% SOC, battery 1 88% SOC and Battery 2 91% SOC. All dynamic and no problems noticed.

**Comment by SwiftRR** [comment]
OK.
I have repeated the process of upgrading from v2.4.9 to v3.0.4
The process was smooth and all the entities are visible.
However, on restarting HA, all Battery details entities become unknown and no details can be seen. 
(_At least that is my experience_). 

It is easiest to view this from Devices @ Services/Integrations/MQTT devices
Screenshots below:
<img width="360" alt="image" src="https://github.com/user-attachments/assets/eef891f7-6fe7-4896-907d-dbb85db09f3b">

I am running HAOS on a raspberry pi with a 500 Gb SSD. (No disk size problem with only 5% used).
I have a GE AC3 inverter daisy chained to two 8.2 kWh batteries.
I am running Predbat (standalone so no appdaemon to muddy the waters).
I have latest versions of HA: 
<img width="597" alt="image" src="https://github.com/user-attachments/assets/ba6d6bed-2c3f-4c70-bde3-bf1ad20d4caf">

I have now downgraded again from v3.0.4 to v2.4.9.
All the battery details are present and after restarting HA battery details are still there.

Can someone who has successfully upgraded from v2.4.9 to v3.0.4 try restarting HA and seeing if their battery details are still there.

The issues might be within my set up in which case I am tempted to completely reinstall HA afresh.

Rob

**Comment by stevedundee2** [comment]
I did an HA restart just now and everything seems to be OK. Battery values are present and changing (the sun set half an hour ago so the battery is now discharging and its SOC is decreasing).

Compared to you my Supervisor version is 2024.11.2, but otherwise the same, including having predbat as an add-on. I have a single, 9.5kWh battery with an inverter model number GIV-HY5.0.

Good luck!

**Comment by SwiftRR** [comment]
Thanks.

I will stick with v2.4.9 for now .....

I wouldn't have spotted this at all had I not had to restart HA at some stage.
But why would restarting HA cause my Battery details entities to become unknown in v3 (and to still be there in v2.4.9)?

Rob

**Comment by stevedundee2** [comment]
Did you restart because you got a Supervisor update, I wonder? In which case, I am doomed! We'll see. Hopefully it has to do with having more than one battery...

I think you are right to stick with what works for now. Reinstalling HA when you don't even know that it would make any difference sounds like too much work,

Perhaps raise a Bug for it? I don't know whether the developer necessarily follows discussion threads like this.

**Comment by SwiftRR** [comment]
I have stumbled on this error which looks relevant in HA Core logs:
<img width="968" alt="image" src="https://github.com/user-attachments/assets/9f4c43d4-a529-4f83-ade6-457e645e7e78">

I will investigate and would appreciate any suggestions for tracking this down.

Rob

**Comment by SwiftRR** [comment]
Thanks.

A great lead and looks like I will be revisiting MQTT Explorer later.
Anything not to have to start again with HA ......
The irony is that I contributed to #23 which was all about duplicate entities. But that was nearly 2 months ago.

It is so confusing seeing duplicates in MQTT Explorer but not knowing which to delete.
And there are so many. My version of MQTT Explorer only allows 50 connections to be deleted each time.

I will update you on any success (or otherwise).
I have come to be a dab hand at bouncing between v2.4.9 and v3, and back again.

Rob

**Comment by gcoan** [comment]
I suspect the problem is that we're seeing what Mark reported first on our v3 upgrades, namely that the upgrade (as opposed to clean install) doesn't correctly remove and recreate the battery MQTT topics.
I think I saw that v3 the MQTT structure has changed slightly.

So if you shutdown v2, delete the battery topics with MQTT explorer, restart MQTT and HA, then start v3,  .... it might cure the problem

**Comment by SwiftRR** [comment]
I am in the process of upgrading to v3.04 again. I will that start deleting MQTT connections using MQTT Explorer. I am checking back through threads to make sure I am doing this correctly. It seems it is duplicated battery entries in the home assistant area. You picked this up originally and I also found the duplicates.

I will report back with my (successful?) results!

Rob

**Comment by SwiftRR** [comment]
I have now removed all the battery details connections in homeassistant using MQTT Explorer.
The connections have now been regenerated but this time there are no duplicates.
The Battery Details entities look good and the details survive restarting HA.

So ..... I am hopeful that I have successfully upgraded from givTCP v2.4.9 to v3.0.4 😁. 
It has taken me long enough.

So, you know what you need to do now when you go for the upgrade.

v3.0.4 does look slicker than v2.4.9 and it will be good to see how it performs.
But I must hand it to v2.4.9 for behaving as running so well.

Upgrading v2 to v3 has this big potential elephant trap!

Rob
